default_language_version:
  python: python3.8

files: (symchk/|README.md)

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: check-added-large-files
      - id: check-ast
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.27.1
    hooks:
      - id: markdownlint

  - repo: https://github.com/psf/black
    rev: 21.6b0
    hooks:
      - id: black

  - repo: https://github.com/pycqa/isort
    rev: 5.8.0
    hooks:
        - id: isort
          args: ["--profile", "black"]

  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
      - id: flake8
        args: ["--ignore=E203,E231,E501,W503", "--max-complexity=10"]

  - repo: https://github.com/jendrikseipp/vulture
    rev: v2.3
    hooks:
      - id: vulture
        args: ["--min-confidence=100", "symchk/"]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.902
    hooks:
      - id: mypy
        args: [--ignore-missing-imports]
        additional_dependencies: [types-requests]
